[project]
name = "live-interface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blivedm",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "obsws-python>=1.8.0",
    "pygame>=2.6.1",
    "pyinstaller>=6.22.2",
    "pyside6>=6.11.1",
    "qasync>=0.28.0",
    "uvicorn>=0.52.4",
]

[tool.uv.sources]
blivedm = { git = "https://github.com/xfgryujk/blivedm.git", branch = "master" }
